name: CI

on:
  push:
    branches: 
      - master
  # 手动触发
  workflow_dispatch:
  # 工作
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x gradlew
          docker compose up


  #发布构建的app
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v2
        with:
            name: Release_${{ env.VERSION }}.apk
            path: ${{ github.workspace }}/app/build/outputs/apk/release/${{ env.APK_FILE }}
